version: '2'

services:
  migrations:
    image: local/msa-example-db-mgmt:1.0.1
    container_name: migrations
    depends_on:
      - db
    environment: 
      - DB_NAME=restapi
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USERNAME=myuser
      - DB_PASSWORD=/run/secrets/db_password
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=restapi

  app:
    image: 'local/msa-example-rest-api:1.0.2'
    ports:
      - 8080:8080
    container_name: app
    depends_on:
      - db
    environment:
      - PRELOAD_SAMPLE_DATA=false
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=restapi
      - DB_USERNAME=myuser
      - DB_PASSWORD=/run/secrets/db_password

secrets:
   db_password:
     file: secrets_db_password

volumes:
    db_data:
